name: Kubernetes Deploy

on:
  workflow_call:
    inputs:
      applicationId:
        description: "The data otter ID of the application"
        required: false
        type: number
      monitorIds:
        description: "List of data otter monitor IDs to disable during deployment"
        required: false
        type: string
      environment:
        description: 'Environment'
        type: string
        required: true
      deploymentName:
        description: "The name of the Kubernetes deployment to update"
        required: true
        type: string
      imageName:
        description: "The name of the Docker image to deploy"
        required: true
        type: string

jobs:
  build:
    permissions:
      contents: read
      packages: read
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup java
        uses: actions/setup-java@v4
        with:
          java-version: '25'
          distribution: 'temurin'

      - name: Build project
        run: mvn clean install

      - name: Build the Docker image
        run: docker build -f Dockerfile .

      - name: Log in to the Container registry
        uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Extract metadata (tags, labels) for Docker
        id: meta
        uses: docker/metadata-action@9ec57ed1fcdbf14dcef7dfbe97b2010124a938b7
        with:
          images: ghcr.io/${{ github.repository }}

      - name: Build and push Docker images
        uses: docker/build-push-action@v5
        with:
          context: .
          file: Dockerfile
          push: true
          tags: ghcr.io/zgamelogic/${{ inputs.imageName }}:${{ inputs.environment }}
          labels: ${{ steps.meta.outputs.labels }}
          build-args: SPRING_PROFILES_ACTIVE=${{ inputs.environment }}

  disable-monitor:
    uses: ./.github/workflows/monitor-status.yaml
    if: ${{ inputs.environment == 'production' && inputs.applicationId && inputs.monitorIds }}
    needs: build
    with:
      applicationId: ${{ inputs.applicationId }}
      monitorId: ${{ inputs.monitorIds }}
      active: false

  Kubernetes:
    runs-on: PiServer
    environment: ${{ inputs.environment }}
    needs: disable-monitor
    if: ${{ !cancelled() && (needs.disable-monitor.result == 'success' || needs.disable-monitor.result == 'skipped') && needs.build.result == 'success' }}
    steps:
      - name: Checkout Kubernetes Directory
        uses: actions/checkout@v4
        with:
          sparse-checkout: 'kubernetes/'

      - name: Apply Kubernetes Configuration
        run: sudo kubectl apply -f kubernetes/${{inputs.environment}} -n ${{ inputs.environment }}

      - name: Rolling update
        run: sudo kubectl rollout restart deployment ${{ inputs.deploymentName }} -n ${{ inputs.environment }}

      - name: Wait for readiness probe
        if: ${{ inputs.environment == 'production' }}
        run: sudo kubectl rollout status deployment ${{ inputs.deploymentName }} -n ${{ inputs.environment }} --timeout=600s

  enable-monitor:
    uses: ./.github/workflows/monitor-status.yaml
    if: ${{ !cancelled() && needs.disable-monitor.result == 'success' }}
    needs: [ Kubernetes, disable-monitor ]
    with:
      applicationId: ${{ inputs.applicationId }}
      monitorId: ${{ inputs.monitorIds }}
      active: true